name: jupyterhub_py3

dependencies:
  - python=3.4
  - nomkl
  # TODO do we need anything from below?
  - ipython-notebook=4.0.4
  - matplotlib=1.5.1
  - numpy=1.10.4
  - pandas=0.17.1
  - scikit-learn=0.17
  - scipy=0.17.0
  - six=1.10.0
  - pip:
    - jupyterhub
